# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ohhello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ohhello.proto',
  package='ohhello',
  serialized_pb=_b('\n\rohhello.proto\x12\x07ohhello\"I\n\nPieceRules\x12\x12\n\npieceIndex\x18\x02 \x02(\r\x12\'\n\x0b\x63urrentRule\x18\x03 \x03(\x0e\x32\x12.ohhello.PieceRule\"F\n\x05Piece\x12\x12\n\npieceIndex\x18\x02 \x02(\r\x12)\n\x0c\x63urrentValue\x18\x03 \x02(\x0e\x32\x13.ohhello.PieceValue\"\x99\x01\n\x05\x46ield\x12\x0e\n\x06gameID\x18\x01 \x02(\r\x12\x1a\n\x12numberOfDimensions\x18\x02 \x02(\r\x12\x1c\n\x10\x64imensionLengths\x18\x03 \x03(\rB\x02\x10\x01\x12\x1d\n\x05\x66ield\x18\n \x03(\x0b\x32\x0e.ohhello.Piece\x12\'\n\nfieldRules\x18\x14 \x03(\x0b\x32\x13.ohhello.PieceRules\"6\n\x04Move\x12\x0e\n\x06gameID\x18\x01 \x02(\r\x12\x1e\n\x06\x63hange\x18\x05 \x02(\x0b\x32\x0e.ohhello.Piece**\n\nPieceValue\x12\t\n\x05UNSET\x10\x00\x12\x07\n\x03RED\x10\x01\x12\x08\n\x04\x42LUE\x10\x02*%\n\tPieceRule\x12\x0c\n\x08UNLOCKED\x10\x00\x12\n\n\x06LOCKED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PIECEVALUE = _descriptor.EnumDescriptor(
  name='PieceValue',
  full_name='ohhello.PieceValue',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=385,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_PIECEVALUE)

PieceValue = enum_type_wrapper.EnumTypeWrapper(_PIECEVALUE)
_PIECERULE = _descriptor.EnumDescriptor(
  name='PieceRule',
  full_name='ohhello.PieceRule',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNLOCKED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCKED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=429,
  serialized_end=466,
)
_sym_db.RegisterEnumDescriptor(_PIECERULE)

PieceRule = enum_type_wrapper.EnumTypeWrapper(_PIECERULE)
UNSET = 0
RED = 1
BLUE = 2
UNLOCKED = 0
LOCKED = 1



_PIECERULES = _descriptor.Descriptor(
  name='PieceRules',
  full_name='ohhello.PieceRules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pieceIndex', full_name='ohhello.PieceRules.pieceIndex', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentRule', full_name='ohhello.PieceRules.currentRule', index=1,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=99,
)


_PIECE = _descriptor.Descriptor(
  name='Piece',
  full_name='ohhello.Piece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pieceIndex', full_name='ohhello.Piece.pieceIndex', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentValue', full_name='ohhello.Piece.currentValue', index=1,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=171,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='ohhello.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameID', full_name='ohhello.Field.gameID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numberOfDimensions', full_name='ohhello.Field.numberOfDimensions', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dimensionLengths', full_name='ohhello.Field.dimensionLengths', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='field', full_name='ohhello.Field.field', index=3,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fieldRules', full_name='ohhello.Field.fieldRules', index=4,
      number=20, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=327,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='ohhello.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameID', full_name='ohhello.Move.gameID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change', full_name='ohhello.Move.change', index=1,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=383,
)

_PIECERULES.fields_by_name['currentRule'].enum_type = _PIECERULE
_PIECE.fields_by_name['currentValue'].enum_type = _PIECEVALUE
_FIELD.fields_by_name['field'].message_type = _PIECE
_FIELD.fields_by_name['fieldRules'].message_type = _PIECERULES
_MOVE.fields_by_name['change'].message_type = _PIECE
DESCRIPTOR.message_types_by_name['PieceRules'] = _PIECERULES
DESCRIPTOR.message_types_by_name['Piece'] = _PIECE
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.enum_types_by_name['PieceValue'] = _PIECEVALUE
DESCRIPTOR.enum_types_by_name['PieceRule'] = _PIECERULE

PieceRules = _reflection.GeneratedProtocolMessageType('PieceRules', (_message.Message,), dict(
  DESCRIPTOR = _PIECERULES,
  __module__ = 'ohhello_pb2'
  # @@protoc_insertion_point(class_scope:ohhello.PieceRules)
  ))
_sym_db.RegisterMessage(PieceRules)

Piece = _reflection.GeneratedProtocolMessageType('Piece', (_message.Message,), dict(
  DESCRIPTOR = _PIECE,
  __module__ = 'ohhello_pb2'
  # @@protoc_insertion_point(class_scope:ohhello.Piece)
  ))
_sym_db.RegisterMessage(Piece)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'ohhello_pb2'
  # @@protoc_insertion_point(class_scope:ohhello.Field)
  ))
_sym_db.RegisterMessage(Field)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
  DESCRIPTOR = _MOVE,
  __module__ = 'ohhello_pb2'
  # @@protoc_insertion_point(class_scope:ohhello.Move)
  ))
_sym_db.RegisterMessage(Move)


_FIELD.fields_by_name['dimensionLengths'].has_options = True
_FIELD.fields_by_name['dimensionLengths']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
